sonar.exclusions=flutterapp/android/**,flutterapp/ios/**,flutterapp/build/**,flutterapp/web/**,flutterapp/linux/**,flutterapp/macos/**,flutterapp/windows/**
source.language=dart
sonar.sourceEncoding=UTF-8
