name: Flutter CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./flutterapp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x' 
          channel: 'stable'
          cache: true 

      - name: instala dependencias
        run: flutter pub get

      - name: verifica formatação
        run: dart format --output=none --set-exit-if-changed .

      - name: analisa código
        run: flutter analyze

      - name: roda testes
        run: flutter test

      - name: build apk
        run: flutter build apk --debug