name: Flutter CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./flutterapp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.6' 
          channel: 'stable'
          cache: true 

      - name: instala dependencias
        run: flutter pub get

      - name: instalar DCDG
        run: dart pub global activate dcdg

      - name: gerar estrutura do diagrama de classes
        run: dart pub global run dcdg -o diagrama.puml

      - name: instalar Graphviz e PlantUML no runner
        run: sudo apt-get update && sudo apt-get install -y graphviz plantuml

      - name: gerar a imagem do diagrama
        run: plantuml diagrama.puml

      - name: salvar imagem do diagrama como artefato
        uses: actions/upload-artifact@v4
        with:
          name: diagrama-classes-uml
          path: flutterapp/diagrama.png

      - name: verificar formatação
        run: dart format --output=none --set-exit-if-changed .

      - name: analisa código
        run: flutter analyze

      - name: verificar código duplicado
        run: npx jscpd ./lib --threshold 0

      - name: roda testes
        run: flutter test

      - name: build apk
        run: flutter build apk --debug

      